name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Contributions
        uses: Platane/snk@v4
        with:
          github_user_name: pranjal-coders
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: contribution-snake
          path: dist/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
